import type { Metadata } from "next";
import { Inter, Raleway } from "next/font/google";
import Navbar from "@/components/Nav/Navbar";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });
const raleway = Raleway({ subsets: ["latin"], variable: "--font-raleway" });

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${raleway.variable}`}>
        {children}
      </body>
    </html>
  );
}
